In [4]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/Muhanad-husn/Sleep-Health-and-Lifestyle/refs/heads/main/data.csv")
df

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

# Q.1) What is the distribution of stress level categories across different quality of sleep categories?

In [11]:
#  distribution of stress level categories across different quality of sleep categories
pd.crosstab(df["Stress Level"], df["Quality of Sleep"])

Quality of Sleep  4  5   6   7   8   9
Stress Level
3                 0  0   0   0   2  69
4                 0  0   0  25  43   2
5                 0  0   0   7  60   0
6                 0  0   4  38   4   0
7                 0  7  36   7   0   0
8                 5  0  65   0   0   0

In [10]:
df.groupby("Stress Level")[["Quality of Sleep"]].agg("count")

              Quality of Sleep
Stress Level
3                           71
4                           70
5                           67
6                           46
7                           50
8                           70

#
--------

# Q.2)  What is the probability that a randomly selected individual has a stress level of 5?

In [18]:
from scipy.stats import norm
mean = df["Stress Level"].mean()
std = df["Stress Level"].std()

probability = norm.cdf(5, loc=mean, scale=std)
print("Probability that stress level <= 5:", probability)

Probability that stress level <= 5: 0.4141141637003654

#
-----

# Q.3)  What is the probability that a randomly selected individual has a quality of sleep score of 7?

In [17]:
mean = df["Quality of Sleep"].mean()
std = df["Quality of Sleep"].std()

probability = norm.cdf(7, loc=mean, scale=std)
print("Probability that stress level <= 7:", probability)

Probability that stress level <= 7: 0.39690815074989516

##
--------

# Q.4)  What is the probability that a randomly selected individual has a stress level at least 5?

In [20]:
mean = df["Stress Level"].mean()
std = df["Stress Level"].std()

probability = 1 - norm.cdf(5, loc=mean, scale=std)
print("Probability that stress level >= 5:", probability)

Probability that stress level >= 5: 0.5858858362996346

##
------

# Q.5)  What is the probability that a randomly selected individual has a stress level at most 7?

In [21]:
mean = df["Stress Level"].mean()
std = df["Stress Level"].std()

probability = norm.cdf(7, loc=mean, scale=std)
print("Probability that stress level <= 7:", probability)

Probability that stress level <= 7: 0.8186116574246284

##
-------

# Q.6)  What is the probability that an individual has a stress level of 7 and a sleep quality score of 6?

In [22]:
probability = ((df["Stress Level"] == 7) & (df["Quality of Sleep"] == 6)).mean()
print("Probability:", probability)

Probability: 0.0962566844919786

#
-------

# Q.7)  What is the probability that an individual has stress level 6 and sleep quality score 7?

In [23]:
probability = ((df["Stress Level"] == 6) & (df["Quality of Sleep"] == 7)).mean()
print("Probability:", probability)

Probability: 0.10160427807486631

#
-----

# Q.8)  What is the probability that an individual has stress level 4 and sleep quality score 8?

In [24]:
probability = ((df["Stress Level"] == 4) & (df["Quality of Sleep"] == 8))
print("Probability:", probability)

Probability: 0      False
1      False
2      False
3      False
4      False
       ...
369    False
370    False
371    False
372    False
373    False
Length: 374, dtype: bool

#
-----

# Q.9)  What is the probability that an individual has stress level 3 and sleep quality score 9?

In [25]:
probability = ((df["Stress Level"] == 3) & (df["Quality of Sleep"] == 9))
print("Probability:", probability)

Probability: 0      False
1      False
2      False
3      False
4      False
       ...
369     True
370     True
371     True
372     True
373     True
Length: 374, dtype: bool

#
----

# Q.10)  If an individual has a stress level of 5, what is the probability that their sleep quality score is 8?

In [30]:
prob_5 = df[df["Stress Level"] == 5]
prob_8 = (prob_5["Quality of Sleep"] == 8).mean()
print(prob_8)

0.8955223880597015

#
----

# Q.11)  If an individual has a stress level of 6, what is the probability that their sleep quality score is 7?

In [36]:
prob_6 = df[df["Stress Level"] == 6]
prob_7 = (prob_6["Quality of Sleep"] == 7).mean()
print(prob_7)

0.8260869565217391

#
------

# Q.12)  If an individuals sleep quality score is 6, what is the probability that their stress level is 7?

In [35]:
prob_6 = df[df["Quality of Sleep"] == 6]
prob_7 = (prob_6["Stress Level"] == 7).mean()
print(prob_7)

0.34285714285714286

#
-----

# Q.13)  If an individuals sleep quality score is 9, what is the probability that their stress level is 3?

In [38]:
prob_9 = df[df["Quality of Sleep"] == 9]
prob_3 = (prob_9["Stress Level"] == 3).mean()
print(prob_3)

0.971830985915493

##
------

# Q.14)  Perform an independence analysis on the variables Stress Level and Quality of Sleep, and summarize your findings based on the results.

In [39]:
correlation = df["Stress Level"].corr(df["Quality of Sleep"])
print("Correlation:", correlation)

Correlation: -0.8987520310040424

# Summary :-
## I performed a correlation analysis between Stress Level and Quality of Sleep. The results show a negative relationship, meaning that as stress level increases, sleep quality decreases. ##

#
-------